<?php
class OpenAiCvService {
 public function available(){return defined('OPENAI_API_KEY')&&trim((string)OPENAI_API_KEY)!=='';}
 public function analyze($cvText,array $criteria,$model=null){
  if(!$this->available())return ['ok'=>false,'message'=>'OpenAI API no configurada.'];
  $model=$model?:((defined('OPENAI_CV_MODEL')&&OPENAI_CV_MODEL)?OPENAI_CV_MODEL:'gpt-5.6-luna');
  $redacted=$this->redact($cvText);$schema=['type'=>'object','additionalProperties'=>false,'properties'=>['score'=>['type'=>'number','minimum'=>0,'maximum'=>100],'summary'=>['type'=>'string'],'matches'=>['type'=>'array','items'=>['type'=>'string']],'gaps'=>['type'=>'array','items'=>['type'=>'string']],'evidence'=>['type'=>'array','items'=>['type'=>'string']]],'required'=>['score','summary','matches','gaps','evidence']];
  $payload=['model'=>$model,'store'=>false,'reasoning'=>['effort'=>'low'],'input'=>[['role'=>'system','content'=>[['type'=>'input_text','text'=>'Evaluá solamente los criterios publicados. No infieras ni uses edad, género, nacionalidad, domicilio, salud, foto, nombre ni otros atributos protegidos. No decidas contratación ni descarte. Devolvé evidencia breve del texto.']] ],['role'=>'user','content'=>[['type'=>'input_text','text'=>"CRITERIOS:\n".json_encode($criteria,JSON_UNESCAPED_UNICODE)."\n\nCV REDACTADO:\n".mb_substr($redacted,0,50000)]]]],'text'=>['format'=>['type'=>'json_schema','name'=>'cv_ranking','strict'=>true,'schema'=>$schema]]];
  $ch=curl_init('https://api.openai.com/v1/responses');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>60,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.OPENAI_API_KEY,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode($payload)]);$body=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($body===false||$code<200||$code>=300)return['ok'=>false,'message'=>'Error de IA '.($err?:$code)];$json=json_decode($body,true);$text='';foreach($json['output']??[] as $item)foreach($item['content']??[] as $content)if(($content['type']??'')==='output_text'){$text=$content['text']??'';break 2;}$result=json_decode($text,true);if(!is_array($result)||!isset($result['score']))return['ok'=>false,'message'=>'Respuesta de IA inválida.'];return['ok'=>true,'result'=>$result,'model'=>$model,'redaction_hash'=>hash('sha256',$redacted)];
 }
 private function redact($text){$text=preg_replace('/\b\d{7,11}\b/u','[DATO OMITIDO]',$text);$text=preg_replace('/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/u','[EMAIL OMITIDO]',$text);$text=preg_replace('/(?:\+?\d[\s()-]*){8,}/u','[TELÉFONO OMITIDO]',$text);$text=preg_replace('/^(?:nombre|apellido|dni|documento|edad|fecha de nacimiento|género|sexo|nacionalidad|domicilio|dirección|estado civil|salud)\s*[:\-].*$/imu','$1: [DATO OMITIDO]',$text);return trim($text);}
}
