<?php
$record = $data['employee_record'] ?? ['ready' => false];
if (empty($record['ready'])): ?>
<hr class="my-4">
<div class="alert alert-warning small mb-3">
    El legajo ampliado no está instalado. Ejecutá <code>migration_employee_record_complete.sql</code>.
</div>
<?php return; endif;
$assignment = $record['assignment'] ?? null;
$address = $record['address'] ?? null;
$coverage = $record['coverage'] ?? null;
$rv = function ($postKey, $object, $property = null, $default = '') use ($data) {
    if (array_key_exists($postKey, $data)) return (string)$data[$postKey];
    $property = $property ?: $postKey;
    return is_object($object) && isset($object->$property) ? (string)$object->$property : $default;
};
?>
<hr class="my-4">
<h6 class="mb-3 text-muted"><i class="fas fa-briefcase me-1"></i> Legajo y relación laboral</h6>
<p class="small text-muted">El rol de acceso se administra arriba. Estos datos describen el puesto laboral y conservan la relación principal compatible con empresa, área y convenio.</p>
<div class="row">
    <div class="col-md-4 mb-3"><label class="form-label" for="employee_number">Número de legajo</label><input class="form-control" id="employee_number" name="employee_number" maxlength="50" value="<?php echo htmlspecialchars($rv('employee_number',$assignment)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="position_id">Puesto / cargo</label><select class="form-select <?php echo isset($data['errors']['position_id'])?'is-invalid':''; ?>" id="position_id" name="position_id"><option value="0">— Sin definir —</option><?php $positionId=(int)$rv('position_id',$assignment); foreach (($record['positions']??[]) as $position): ?><option value="<?php echo (int)$position->id; ?>" <?php echo $positionId===(int)$position->id?'selected':''; ?>><?php echo htmlspecialchars($position->name); ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?php echo htmlspecialchars($data['errors']['position_id']??''); ?></div><div class="form-text"><a href="<?php echo URLROOT; ?>/admin/employeeCatalogs" target="_blank">Administrar puestos y coberturas</a>.</div></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="cost_center">Centro de costo</label><input class="form-control" id="cost_center" name="cost_center" maxlength="80" value="<?php echo htmlspecialchars($rv('cost_center',$assignment)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="supervisor_user_id">Jefe directo</label><?php $supervisorId=(int)$rv('supervisor_user_id',$assignment); ?><select class="form-select <?php echo isset($data['errors']['supervisor_user_id'])?'is-invalid':''; ?>" id="supervisor_user_id" name="supervisor_user_id"><option value="0">— Sin definir —</option><?php foreach(($record['supervisors']??[]) as $supervisor): ?><option value="<?php echo (int)$supervisor->id; ?>" <?php echo $supervisorId===(int)$supervisor->id?'selected':''; ?>><?php echo htmlspecialchars($supervisor->full_name); ?> (<?php echo htmlspecialchars($supervisor->role); ?>)</option><?php endforeach; ?></select><div class="invalid-feedback"><?php echo htmlspecialchars($data['errors']['supervisor_user_id']??''); ?></div></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="employment_type">Tipo de contratación</label><?php $et=$rv('employment_type',$assignment,null,'permanente'); ?><select class="form-select" id="employment_type" name="employment_type"><?php foreach(['permanente'=>'Permanente','plazo_fijo'=>'Plazo fijo','eventual'=>'Eventual','temporario'=>'Temporario','practica'=>'Práctica/Pasantía','otro'=>'Otro'] as $k=>$v): ?><option value="<?php echo $k; ?>" <?php echo $et===$k?'selected':''; ?>><?php echo $v; ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="work_mode">Modalidad</label><?php $wm=$rv('work_mode',$assignment,null,'presencial'); ?><select class="form-select" id="work_mode" name="work_mode"><?php foreach(['presencial'=>'Presencial','hibrido'=>'Híbrido','remoto'=>'Remoto'] as $k=>$v): ?><option value="<?php echo $k; ?>" <?php echo $wm===$k?'selected':''; ?>><?php echo $v; ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="employment_status">Estado laboral</label><?php $es=$rv('employment_status',$assignment,'status','activo'); ?><select class="form-select" id="employment_status" name="employment_status"><?php foreach(['preingreso'=>'Preingreso','activo'=>'Activo','licencia'=>'Licencia prolongada','suspendido'=>'Suspendido','finalizado'=>'Finalizado'] as $k=>$v): ?><option value="<?php echo $k; ?>" <?php echo $es===$k?'selected':''; ?>><?php echo $v; ?></option><?php endforeach; ?></select><div class="form-text">Es independiente de la habilitación para iniciar sesión.</div></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="seniority_date">Antigüedad reconocida desde</label><input type="date" class="form-control" id="seniority_date" name="seniority_date" value="<?php echo htmlspecialchars($rv('seniority_date',$assignment)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="employment_end_date">Fecha de finalización</label><input type="date" class="form-control <?php echo isset($data['errors']['employment_end_date'])?'is-invalid':''; ?>" id="employment_end_date" name="employment_end_date" value="<?php echo htmlspecialchars($rv('employment_end_date',$assignment,'end_date')); ?>"><div class="invalid-feedback"><?php echo htmlspecialchars($data['errors']['employment_end_date']??''); ?></div></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="termination_reason">Motivo de finalización</label><input class="form-control" id="termination_reason" name="termination_reason" maxlength="255" value="<?php echo htmlspecialchars($rv('termination_reason',$assignment)); ?>"></div>
</div>

<hr class="my-4">
<h6 class="mb-3 text-muted"><i class="fas fa-map-marker-alt me-1"></i> Domicilio estructurado y georreferencia</h6>
<div class="alert alert-info small">Las coordenadas son datos personales sensibles de acceso exclusivo para RR. HH. El estado “confirmada” implica que el punto fue revisado por una persona.</div>
<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label" for="street">Calle</label><input class="form-control" id="street" name="street" value="<?php echo htmlspecialchars($rv('street',$address)); ?>"></div>
    <div class="col-md-2 mb-3"><label class="form-label" for="street_number">Número</label><input class="form-control" id="street_number" name="street_number" value="<?php echo htmlspecialchars($rv('street_number',$address)); ?>"></div>
    <div class="col-md-2 mb-3"><label class="form-label" for="floor_unit">Piso / unidad</label><input class="form-control" id="floor_unit" name="floor_unit" value="<?php echo htmlspecialchars($rv('floor_unit',$address)); ?>"></div>
    <div class="col-md-2 mb-3"><label class="form-label" for="postal_code">Código postal</label><input class="form-control" id="postal_code" name="postal_code" value="<?php echo htmlspecialchars($rv('postal_code',$address)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="neighborhood">Barrio</label><input class="form-control" id="neighborhood" name="neighborhood" value="<?php echo htmlspecialchars($rv('neighborhood',$address)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="locality">Localidad</label><input class="form-control" id="locality" name="locality" value="<?php echo htmlspecialchars($rv('locality',$address)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="administrative_area">Departamento / partido</label><input class="form-control" id="administrative_area" name="administrative_area" value="<?php echo htmlspecialchars($rv('administrative_area',$address)); ?>"></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="province">Provincia</label><input class="form-control" id="province" name="province" value="<?php echo htmlspecialchars($rv('province',$address)); ?>"></div>
    <div class="col-md-2 mb-3"><label class="form-label" for="country_code">País</label><input class="form-control" id="country_code" name="country_code" maxlength="2" value="<?php echo htmlspecialchars($rv('country_code',$address,null,'AR')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="latitude">Latitud</label><input type="number" step="0.0000001" class="form-control <?php echo isset($data['errors']['latitude'])?'is-invalid':''; ?>" id="latitude" name="latitude" value="<?php echo htmlspecialchars($rv('latitude',$address)); ?>"><div class="invalid-feedback"><?php echo htmlspecialchars($data['errors']['latitude']??''); ?></div></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="longitude">Longitud</label><input type="number" step="0.0000001" class="form-control <?php echo isset($data['errors']['longitude'])?'is-invalid':''; ?>" id="longitude" name="longitude" value="<?php echo htmlspecialchars($rv('longitude',$address)); ?>"><div class="invalid-feedback"><?php echo htmlspecialchars($data['errors']['longitude']??''); ?></div></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="address_verification_status">Validación</label><?php $avs=$rv('address_verification_status',$address,'verification_status','pendiente'); ?><select class="form-select" id="address_verification_status" name="address_verification_status"><option value="pendiente" <?php echo $avs==='pendiente'?'selected':''; ?>>Pendiente</option><option value="confirmada" <?php echo $avs==='confirmada'?'selected':''; ?>>Confirmada en mapa</option><option value="manual" <?php echo $avs==='manual'?'selected':''; ?>>Corregida manualmente</option></select></div>
    <div class="col-12 mb-3"><label class="form-label" for="reference_notes">Referencias</label><input class="form-control" id="reference_notes" name="reference_notes" value="<?php echo htmlspecialchars($rv('reference_notes',$address)); ?>"></div>
</div>

<hr class="my-4">
<h6 class="mb-3 text-muted"><i class="fas fa-heartbeat me-1"></i> Obra social / cobertura médica</h6>
<div class="row">
    <div class="col-md-4 mb-3"><label class="form-label" for="health_insurer_id">Cobertura</label><?php $insurerId=(int)$rv('health_insurer_id',$coverage); ?><select class="form-select" id="health_insurer_id" name="health_insurer_id"><option value="0">— Sin informar —</option><?php foreach(($record['insurers']??[]) as $insurer): ?><option value="<?php echo (int)$insurer->id; ?>" <?php echo $insurerId===(int)$insurer->id?'selected':''; ?>><?php echo htmlspecialchars($insurer->display_name); ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="health_plan_id">Plan</label><?php $planId=(int)$rv('health_plan_id',$coverage); ?><select class="form-select" id="health_plan_id" name="health_plan_id"><option value="0">— Sin plan —</option><?php foreach(($record['plans']??[]) as $plan): ?><option data-insurer="<?php echo (int)$plan->health_insurer_id; ?>" value="<?php echo (int)$plan->id; ?>" <?php echo $planId===(int)$plan->id?'selected':''; ?>><?php echo htmlspecialchars($plan->name); ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4 mb-3"><label class="form-label" for="affiliate_number">Número de afiliado</label><input class="form-control" id="affiliate_number" name="affiliate_number" value="<?php echo htmlspecialchars($rv('affiliate_number',$coverage)); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="health_member_role">Carácter</label><?php $hmr=$rv('health_member_role',$coverage,'member_role','titular'); ?><select class="form-select" id="health_member_role" name="health_member_role"><option value="titular" <?php echo $hmr==='titular'?'selected':''; ?>>Titular</option><option value="adherente" <?php echo $hmr==='adherente'?'selected':''; ?>>Adherente</option></select></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="health_status">Estado</label><?php $hs=$rv('health_status',$coverage,'status','activa'); ?><select class="form-select" id="health_status" name="health_status"><?php foreach(['en_tramite'=>'En trámite','activa'=>'Activa','suspendida'=>'Suspendida','finalizada'=>'Finalizada'] as $k=>$v): ?><option value="<?php echo $k; ?>" <?php echo $hs===$k?'selected':''; ?>><?php echo $v; ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="health_start_date">Alta</label><input type="date" class="form-control" id="health_start_date" name="health_start_date" value="<?php echo htmlspecialchars($rv('health_start_date',$coverage,'start_date')); ?>"></div>
    <div class="col-md-3 mb-3"><label class="form-label" for="health_end_date">Baja</label><input type="date" class="form-control" id="health_end_date" name="health_end_date" value="<?php echo htmlspecialchars($rv('health_end_date',$coverage,'end_date')); ?>"></div>
    <div class="col-12 mb-3"><div class="form-check"><input type="checkbox" class="form-check-input" id="contribution_redirected" name="contribution_redirected" value="1" <?php echo (int)$rv('contribution_redirected',$coverage)?'checked':''; ?>><label class="form-check-label" for="contribution_redirected">Aportes derivados a esta cobertura</label></div></div>
</div>
<script>
(function(){var insurer=document.getElementById('health_insurer_id'),plan=document.getElementById('health_plan_id');if(!insurer||!plan)return;function filter(){Array.from(plan.options).forEach(function(o){if(!o.dataset.insurer)return;o.hidden=insurer.value!=='0'&&o.dataset.insurer!==insurer.value;});if(plan.selectedOptions[0]&&plan.selectedOptions[0].hidden)plan.value='0';}insurer.addEventListener('change',filter);filter();})();
</script>
