<?php
class PerformanceController {
    private $m;
    public function __construct(){if(!isStaffAdmin())redirect('login');$this->m=new HrSuite();}
    public function index(){require_capability('performance.evaluate');$cid=requireAdminCompany();$this->view('admin/performance/index',['templates'=>$this->m->query('SELECT * FROM performance_templates WHERE company_id=? ORDER BY name',[$cid]),'cycles'=>$this->m->performanceCycles($cid),'users'=>(new User())->getUsersByCompany($cid)]);}
    public function saveTemplate(){require_capability('performance.manage');$this->post();$ow=(float)($_POST['objectives_weight']??50);$cw=(float)($_POST['competencies_weight']??50);if(abs(($ow+$cw)-100)>0.01){$_SESSION['flash_error']='Las ponderaciones deben sumar 100.';redirect('performance/index');}$definition=['objectives'=>$this->lines($_POST['objectives']??''),'competencies'=>$this->lines($_POST['competencies']??'')];$this->m->execute('INSERT INTO performance_templates(company_id,name,method,objectives_weight,competencies_weight,definition_json) VALUES(?,?,?,?,?,?)',[adminCompanyId(),trim($_POST['name']),($_POST['method']??'180')==='90'?'90':'180',$ow,$cw,json_encode($definition,JSON_UNESCAPED_UNICODE)]);$this->m->audit()->record('performance.template.created','performance_template',$this->m->one('SELECT LAST_INSERT_ID() id')->id,null,$definition,'',adminCompanyId());redirect('performance/index');}
    public function saveCycle(){require_capability('performance.manage');$this->post();$this->m->execute("INSERT INTO performance_cycles(company_id,template_id,name,starts_on,ends_on,status,created_by) VALUES(?,?,?,?,?,'open',?)",[adminCompanyId(),(int)$_POST['template_id'],trim($_POST['name']),$_POST['starts_on'],$_POST['ends_on'],(int)$_SESSION['user_id']]);$cycle=$this->m->one('SELECT LAST_INSERT_ID() id')->id;foreach((array)($_POST['subjects']??[]) as $uid){$uid=(int)$uid;$this->m->execute("INSERT IGNORE INTO performance_reviews(cycle_id,subject_user_id,reviewer_user_id,reviewer_type) VALUES(?,?,?,'self')",[$cycle,$uid,$uid]);if(!empty($_POST['manager_user_id']))$this->m->execute("INSERT IGNORE INTO performance_reviews(cycle_id,subject_user_id,reviewer_user_id,reviewer_type) VALUES(?,?,?,'manager')",[$cycle,$uid,(int)$_POST['manager_user_id']]);}$this->m->audit()->record('performance.cycle.opened','performance_cycle',$cycle,null,['subjects'=>$_POST['subjects']??[]],'',adminCompanyId());redirect('performance/index');}
    public function review($id){require_capability('performance.evaluate');$r=$this->reviewRow($id);if(!$r){http_response_code(404);exit;}$this->view('admin/performance/review',['review'=>$r,'definition'=>json_decode($r->definition_json,true)?:[],'answers'=>json_decode($r->answers_json??'',true)?:[]]);}
    public function submit($id){require_capability('performance.evaluate');$this->post();$r=$this->reviewRow($id);if(!$r)redirect('performance/index');$answers=(array)($_POST['scores']??[]);$comments=trim($_POST['comments']??'');$values=array_values(array_filter(array_map('floatval',$answers),fn($v)=>$v>=1&&$v<=5));$score=$values?array_sum($values)/count($values):null;$this->m->execute("UPDATE performance_reviews SET answers_json=?,raw_score=?,status='submitted',submitted_at=NOW() WHERE id=?",[json_encode(['scores'=>$answers,'comments'=>$comments],JSON_UNESCAPED_UNICODE),$score,$id]);$this->m->audit()->record('performance.review.submitted','performance_review',$id,null,['score'=>$score],'',adminCompanyId());redirect('performance/index');}
    public function close($id){require_capability('performance.calibrate');$this->post();$this->m->execute("UPDATE performance_cycles SET status='closed',closed_by=? WHERE id=? AND company_id=?",[(int)$_SESSION['user_id'],(int)$id,adminCompanyId()]);$this->m->audit()->record('performance.cycle.closed','performance_cycle',$id,null,['status'=>'closed'],trim($_POST['reason']??''),adminCompanyId());redirect('performance/index');}
    private function reviewRow($id){return $this->m->one('SELECT pr.*,pc.company_id,pc.status cycle_status,pt.definition_json,u.full_name subject_name FROM performance_reviews pr JOIN performance_cycles pc ON pc.id=pr.cycle_id JOIN performance_templates pt ON pt.id=pc.template_id JOIN users u ON u.id=pr.subject_user_id WHERE pr.id=? AND pc.company_id=?',[(int)$id,adminCompanyId()]);}
    private function lines($s){return array_values(array_filter(array_map('trim',preg_split('/\r?\n/',$s))));}
    private function post(){if($_SERVER['REQUEST_METHOD']!=='POST')redirect('performance/index');csrf_verify();}
    private function view($v,$d){require APPROOT.'/views/'.$v.'.php';}
}
